# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Solabile
email: konnekerl@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Solar-powered Calder mobiles, kinetic sculpture, chimes, ultra-low power electronics, IOT.



# Since this is a "project" site on github, the baseurl is the project name "solabile"
baseurl: "/solabile" # the subpath of your site, e.g. /blog
# This works when served at Github.
# To work locally, use     jekyll serve --baseurl ''
# However, Jekyll relies on this to find theme and style, so don't change it.

# Define our own variable for pages other than the top and about
#pages_url: "https://bootchk.github.io/solabile/pages"
pages_url: "./pages"

# internal links for a page should be: ( {{site.baseurl}}/pages/foo.html )

# Setting this to https interferes with local testing which uses straight http
# url: "https://bootchk.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#twitter_username: jekyllrb
github_username:  bootchk

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

header_pages:
  - about.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - vagga.yaml
   - .vagga/
   - .git/
   - .home/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - .jekyll-cache/

#    - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
